Code/PhimCoDoc/DVMN/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DVMN.Models
{
    public class Film : Base
    {
        private IList<string> _genres = new List<string>();
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ID { get; set; }
        [DisplayName("Tiêu đề")]
        public string Title { get; set; }
        public string OrtherTitle { get; set; }
        [DisplayName("Nội dung ngắn")]
        public string DescriptionShort { get; set; }
        public string Description { get; set; }

        [DisplayName("Ngày xuất bản")]
        public DateTime? DateofRease { get; set; }
        public string Actor { get; set; }
        
        public string Director { get; set; }

        public int Vote { get; set; }

        public bool IsProposed { get; set; }
        public string Info { get; set; }
        public string Length { get; set; }
        public int Watch { get; set; }
        public float StarRating { get; set; }
        public string Video { get; set; }
        public string VideoBackUp1 { get; set; }
        public string VideoBackUp2 { get; set; }
        public string VideoTrailer { get; set; }
        public string Slug { get; set; }
        public int? ImageID { get; set; }
        public Images Image { get; set; }
        public int? SerieID { get; set; }
        public Serie Serie { get; set; }

        public string Genres
        {
            get;set;
        }
    }
}

Code/PhimCoDoc/DVMN/Models/FilmViewModels/ProposalFilmViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DVMN.Models.FilmViewModels
{
    public class ProposalFilmViewModel
    {
        public ProposalFilmViewModel(Images image)
        {
            Image = image;
        }
        public int ID { get; set; }
        public Images Image { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        public string Description { get; set; }
        public DateTime? DateOfRelease { get; set; }

        public string VideoTrailler { get; set; }

        public string Genres { get; set; }
        public int Vote { get; set; }
    }
}

Code/PhimCoDoc/DVMN/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DVMN.Models
{
    public class Tag
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int ID { get; set; }

        public string Slug { get; set; }

        public string Title { get; set; }
    }
}

Code/PhimCoDoc/DVMN/Areas/WebManager/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DVMN.Data;
using DVMN.Models;
using DVMN.Models.FilmViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace DVMN.Areas.WebManager.Controllers
{
    [Area("WebManager")]
    [Authorize(Roles = "Admin")]
    public class FilmController : Controller
    {
        private readonly IFilmRepository _repository;
        private readonly UserManager<Member> _userManager;

        public FilmController(IFilmRepository repository, UserManager<Member> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }
        [Route("/quan-ly-web/phim")]
        public async Task<IActionResult> Index()
        {
            var posts = await _repository.GetAll();
            return View(posts);
        }

        // GET: WebManager/Film/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _repository.Get(id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: WebManager/Film/Create
        [Route("/quan-ly-web/phim/tao-moi")]
        public IActionResult Create()
        {
            ViewData["ImageID"] = new SelectList(_repository.GetImages(), "ID", "Name");
            ViewData["AuthorID"] = new SelectList(_repository.GetMembers(), "Id", "FullName");
            ViewData["SerieID"] = new SelectList(_repository.GetSeries(), "ID", "Name");
            return View();
        }

        // POST: WebManager/Film/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("/quan-ly-web/phim/tao-moi")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,OrtherTitle,Description, DescriptionShort,TempTag,DateofRease,Info,Length,Watch,StarRating,Video, VideoBackUp1, VideoBackUp2,VideoTrailer,Slug,ImageID,SerieID,Genres,IsProposed,Actor,Director,TempTag")] CreateEditFilmViewModel film)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                film.AuthorID = user.Id;
                await _repository.Create(film);
                return RedirectToAction("Index");
            }
            ViewData["ImageID"] = new SelectList(_repository.GetImages(), "ID", "Name", film.ImageID);
            ViewData["AuthorID"] = new SelectList(_repository.GetMembers(), "Id", "FullName", film.AuthorID);
            ViewData["SerieID"] = new SelectList(_repository.GetSeries(), "ID", "ID", film.SerieID);
            return View(film);
        }

        // GET: WebManager/Film/Edit/5
        [Route("/quan-ly-web/phim/chinh-sua/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _repository.GetEdit(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewData["ImageID"] = new SelectList(_repository.GetImages(), "ID", "Name");
            ViewData["AuthorID"] = new SelectList(_repository.GetMembers(), "Id", "FullName");
            ViewData["SerieID"] = new SelectList(_repository.GetSeries(), "ID", "ID");
            return View(film);
        }

        // POST: WebManager/Film/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("/quan-ly-web/phim/chinh-sua/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,OrtherTitle,Description, DescriptionShort,TempTag,DateofRease,Info,Length,Watch,StarRating,Video, VideoBackUp1, VideoBackUp2,VideoTrailer,Slug,ImageID,SerieID,Genres,IsProposed,Actor,Director,TempTag")] CreateEditFilmViewModel film)
        {
            if (id != film.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repository.SaveEdit(film);
                }
                catch (DbUpdateConcurrencyException)
                {
                    
                        throw;
                }
                return RedirectToAction("Index");
            }
            ViewData["ImageID"] = new SelectList(_repository.GetImages(), "ID", "ID", film.ImageID);
            ViewData["AuthorID"] = new SelectList(_repository.GetMembers(), "Id", "Id", film.AuthorID);
            ViewData["SerieID"] = new SelectList(_repository.GetSeries(), "ID", "ID", film.SerieID);
            return View(film);
        }

        // GET: WebManager/Film/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _repository.Get(id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: WebManager/Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repository.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

Code/PhimCoDoc/DVMN/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DVMN.Data;
using Microsoft.EntityFrameworkCore;

namespace DVMN.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmRepository _repository;

        public FilmController(IFilmRepository repository)
        {
            _repository = repository;
        }

        [Route("/phim/{slug}")]
        public async Task<IActionResult> Single(string slug)
        {
            ViewData["FilmDetials"] = await _repository.Get(slug, "1");
            ViewData["SingleRightFilm"] = await _repository.GetSingleRightFilms();
            ViewData["bannerBottomFilm"] = await _repository.GetBannerBottomFilm();
            await _repository.IsWatched(slug);
            return View();
        }
        [Route("/xem-phim/{slug}")]
        public async Task<IActionResult> Watch(string server, string slug)
        {
            if (String.IsNullOrEmpty(server))
                server = "1";
            ViewData["FilmDetials"] = await _repository.Get(slug, server);
            ViewData["bannerBottomFilm"] = await _repository.GetBannerBottomFilm();
            return View();
        }

        [Route("/tai-phim/{slug}")]
        public async Task<IActionResult> Download(string slug)
        {
            ViewData["FilmDetials"] = await _repository.GetDownloadFilm(slug);
            ViewData["SingleRightFilm"] = await _repository.GetSingleRightFilms();
            ViewData["bannerBottomFilm"] = await _repository.GetBannerBottomFilm();
            return View();
        }
        [Route("phim/the/{slug}")]
        public async Task<IActionResult> Tag ( string slug)
        {
            ViewData["Tag"] = slug;
            return View(await _repository.GetFilmsInTag(slug));
        }


    }
}

Code/PhimCoDoc/DVMN/Controllers/ProposalsFilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DVMN.Data;
using DVMN.Models;

namespace DVMN.Controllers
{
    public class ProposalsFilmController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProposalsFilmController(ApplicationDbContext _context)
        {
            this._context = _context;
        }
        public async Task<string> Send(string name, string reson)
        {
            _context.Add(new ProposalsFilm { Name = name, Reason = reson});
            await _context.SaveChangesAsync();
            return "1";
        }
    }
}

Code/PhimCoDoc/DVMN/Views/Film/ProposalFilm.cshtml
@{ 
    ViewData["Title"] = "Đề cử phim mới | Phim Cơ Đốc";
}

@using DVMN.Models.FilmViewModels
@model IEnumerable<ListProposalFilmViewModel>
<div class="general_social_icons">
    @await Html.PartialAsync("_SocialPartial")
</div>
<!-- general -->
<div class="general">
    <h4 class="latest-text w3_latest_text">Đề cử phim mới</h4>
    <div class="container">

            <!--Max 12 film-->
            @if (!Model.Any())
            {
                <h3>Chưa có film nào cả</h3>
            }

            @foreach (var item in Model)
            {
                <div class="col-md-2 w3l-movie-gride-agile">
                    <a class="hvr-shutter-out-horizontal">
                        <img src="@item.Image.Pic182x268" title="@item.Image.Title" class="img-responsive" alt="@item.Image.ALT" />
                        <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                    </a>
                    <div class="mid-1 agileits_w3layouts_mid_1_home">
                        <div class="w3l-movie-text">
                            <h4><a>@item.Title</a></h4>
                        </div>
                        <div class="mid-2 agile_mid_2_home">
                            <p>@item.OrtherTitle </p>
                            <i class="glyphicon glyphicon-heart"> </i> @item.Vote
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <label class="sub-heading-img">
                        @item.Info
                    </label>
                </div>
            }
            <div class="clearfix"> </div>
        </div>
</div>

Code/PhimCoDoc/DVMN/Views/Film/Single.cshtml
@using DVMN.Models.FilmViewModels
@{
    IEnumerable<GeneralFilmViewModel> generalFilm = ViewData["generalFilm"] as IEnumerable<GeneralFilmViewModel>;
    WatchFilmViewModel filmDetails = ViewData["FilmDetials"] as WatchFilmViewModel;
    IEnumerable<SingleRightPartialFilmViewModel> singleRightFilm = ViewData["SingleRightFilm"] as IEnumerable<SingleRightPartialFilmViewModel>;
    ViewData["Title"] = "Thông tin phim " + filmDetails.Title + " | Phim Cơ Đốc";
    IEnumerable<BannerBottomFilmViewModel> bannerBottomFilm = ViewData["bannerBottomFilm"] as IEnumerable<BannerBottomFilmViewModel>;
    ViewData["Desciption"] = filmDetails.DescriptionShort; 
}

<div class="general_social_icons">
    @await Html.PartialAsync("_SocialPartial")
</div>
<!-- single -->
<div class="single-page-agile-main">
    <div class="container">
        <!-- /w3l-medile-movies-grids -->
        <div class="agileits-single-top">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Trang chủ</a></li>
                <li><a asp-controller="Home" asp-action="Index">Phim</a></li>
                <li class="active">@filmDetails.Title</li>
            </ol>
        </div>
        <div class="single-page-agile-info">
            <!-- /movie-browse-agile -->
            <div class="show-top-grids-w3lagile">
                <div class="col-sm-8 single-left">
                   @await Html.PartialAsync("_SingleLeftPartial", filmDetails)
                </div>
                <div class="col-md-4 single-right" style="border-color: blue; border-width: 1px; border-style: solid;">
                   @await Html.PartialAsync("_SingleRightPartial", singleRightFilm)
                </div>
                <div class="clearfix"> </div>
            </div>
            <!-- //movie-browse-agile -->
            <!--body wrapper start-->
            @await Html.PartialAsync("_BannerBottomPartial", bannerBottomFilm)
            <!--body wrapper end-->
        </div>
        <!-- //w3l-latest-movies-grids -->
    </div>
</div>
@section Style {

}
@section Scripts {

}

Code/PhimCoDoc/DVMN/Views/Film/Tag.cshtml
@{
    ViewData["Title"] = "Phim theo thẻ " + ViewData["Tag"] + " | Phim Cơ Đốc";
    ViewData["Desciption"] = "Tất cả phim Cơ Đốc nằm trong thẻ " + ViewData["Tag"] + " điều hiển thị tại đây";
}

@using DVMN.Models.FilmViewModels
@model IEnumerable<WatchALotFilmViewModel>
    <div class="general_social_icons">
        @await Html.PartialAsync("_SocialPartial")
    </div>
    <!-- general -->
    <div class="general">
        <h4 class="latest-text w3_latest_text">Đề cử phim mới</h4>
        <div class="container">
            <div class="agileits-news-top">
                <ol class="breadcrumb">
                    <li>
                        <a asp-controller="Home" asp-action="Index">Trang chủ</a>
                    </li>
                    <li class="active">Phim xem nhiều</li>
                </ol>
            </div>
            <!--Max 12 film-->
            @if (!Model.Any())
            {
                <h3>Chưa có film nào cả</h3>
            }

            @foreach (var item in Model)
            {
                <div class="col-md-2 w3l-movie-gride-agile">
                    <a asp-controller="Film" asp-action="Single" asp-route-slug="@item.Slug" class="hvr-shutter-out-horizontal">
                        <img src="@item.Image.Pic182x268" title="@item.Image.Title" class="img-responsive" alt="@item.Image.ALT" />
                        <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                    </a>
                    <div class="mid-1 agileits_w3layouts_mid_1_home">
                        <div class="w3l-movie-text">
                            <h4><a asp-controller="Film" asp-action="Single" asp-route-slug="@item.Slug">@item.Title</a></h4>
                        </div>
                        <div class="mid-2 agile_mid_2_home">
                            <p>@item.OrtherTitle </p>
                            <i class="glyphicon glyphicon-eye-open"> </i> @item.Watch
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <label class="sub-heading-img">
                        @item.Info
                    </label>
                </div>
            }
            <div class="clearfix"> </div>
        </div>
    </div>

Code/PhimCoDoc/DVMN/Views/Film/Watch.cshtml
@using DVMN.Models.FilmViewModels;
@{
    WatchFilmViewModel item = ViewData["FilmDetials"] as WatchFilmViewModel;
    IEnumerable<BannerBottomFilmViewModel> bannerBottomFilm = ViewData["bannerBottomFilm"] as IEnumerable<BannerBottomFilmViewModel>;
    string scheme = Context.Request.Scheme;
    string host = Context.Request.Host.Host;
    string port = Context.Request.Host.Port.ToString();
    string path = "/phim/" +item.Slug;
    string url = string.Format("{0}://{1}:{2}{3}", scheme, host, port, path);
    ViewData["Title"] = "Xem phim " + item.Title + " | Phim cơ đốc";
    ViewData["Desciption"] = item.DescriptionShort;
}

<div class="general_social_icons">
    @await Html.PartialAsync("_SocialPartial")
</div>

<!-- single -->
<div class="single-page-agile-main">
    <div class="container">
        <!-- /w3l-medile-movies-grids -->
        <div class="agileits-single-top">
            <ol class="breadcrumb">
                <li><a asp-controller="Home" asp-action="index">Trang chủ</a></li>
                <li><a asp-controller="Home" asp-action="Index">Xem phim</a></li>
                <li class="active">@item.Title</li>
            </ol>
        </div>
        <div class="single-page-agile-info">
            @switch (item.SelectSever)
            {

                case 1:

                    <div class="embed-responsive embed-responsive-16by9">
                        <div class="embed-responsive embed-responsive-16by9" @*style="display:none" *@>
                            @{
                                var Video1 = "https://drive.google.com/file/d/";
                                Video1 += item.Video;
                                Video1 += "/preview?autoplay=1";
                            }
                            <iframe class="video" src="@Video1" frameborder="0" allowfullscreen="1"></iframe>
                        </div>
                    </div>
                                    break;
                                case 2:
                                    @*<div onclick="this.nextElementSibling.style.display='block'; this.style.display='none'">
                                            <img src="@item.Image.Pic1140x641" class="img-responsive" style="cursor:pointer" />
                                        </div>*@
                                    <div class="embed-responsive embed-responsive-16by9" @*style="display:none" *@>
                                        @{
                                            var Video2 = "https://drive.google.com/file/d/";
                                            Video2 += item.Video;
                                            Video2 += "/preview?autoplay=1";
                                        }
                                        <iframe class="video" src="@Video2" frameborder="0" allowfullscreen="1"></iframe>
                                    </div>
                                                    break;
                                                case 3:
                                                    break;
                                            }
            <br />
            <div class="like-share-video-backup">
                <div class="pull-left" style="margin-bottom: 5px;">
                    @if (!String.IsNullOrEmpty(item.Video))
                    {
                        <a asp-action="Watch" class="btn btn-default" asp-controller="Film" asp-route-server="1"><i class="glyphicon glyphicon-film"></i> VIP1 @item.Info</a>
                    }
                    @if (!String.IsNullOrEmpty(item.VideoBackUp1))
                    {
                        <a asp-action="Watch" asp-controller="Film" class="btn btn-success" asp-route-server="2"><i class="glyphicon glyphicon-film"></i> VIP2 @item.Info</a>
                    }
                    @if (!String.IsNullOrEmpty(item.VideoBackUp2))
                    {
                        <a asp-action="Watch" asp-controller="Film" class="btn btn-primary" asp-route-server="3"><i class="glyphicon glyphicon-film"></i> VIP3 @item.Info</a>
                    }
                    <a href="#" class="btn btn-warning" data-toggle="modal" data-target="#reportTranslate"><i class="fa fa-smile-o"></i> Góp ý bản dịch & đề xuất film</a>
                    <button class="switch btn btn-primary"><i class="fa fa-lightbulb-o"></i> Tắt đèn</button>
                </div>
                <div class="pull-right">
                    <div class="fb-like fa-like-watch" data-href="@string.Format("{0}",@url)" data-layout="button_count" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div>
                </div>
            </div>
            <style>
                #persoff {
                    background: #000;
                    opacity: 0.9;
                    filter: alpha(opacity=90);
                    position: fixed;
                    left: 0;
                    top: 0;
                    width: 100%;
                    height: 100%;
                    z-index: 100;
                }
                .video {
                    position: relative;
                    z-index: 102;
                }
            </style>
            <div id="persoff"></div>
            <br /><br />
            <div class="info-video">
                <h2 class="text-primary" style="padding: 10px">@item.Title</h2>
                <h4 class="text-white" style="padding: 10px">@item.OrtherTitle</h4>
                <p>@item.DescriptionShort</p>
            </div>
            <div class="send-and-rating">
                <div class="pull-left">
                    <div class="fb-send" data-href="https://developers.facebook.com/apps"></div>
                    Bấm vào đây để gửi phim cho bạn bè cùng xem
                </div>
                <div class="pull-right">
                    Đánh giá phim (Sắp ra mắt)
                </div>
            </div>

            <div class="fb-comments" data-width="100%" data-href="@string.Format("{0}",@url)" data-numposts="7"></div>
            @*@await Html.PartialAsync("_BannerBottomPartial", bannerBottomFilm)*@
        </div>
    </div>
</div>
@Html.Partial("_ReportTranslatePopupPartial")
@section Scripts {
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/lib/ckeditor/adapters/jquery.js"></script>
    <script src="~/plugins/timepicker/bootstrap-timepicker.js"></script>
    <script>
        //function onClose() {
        //    $("#undo").show();
        //}

        //$(document).ready(function () {
        //    $("#undo").bind("click", function () {
        //        $("#window").data("kendoWindow").open();
        //        $("#undo").hide();
        //    });
        //});
        $(".ckeditor").ckeditor(

        );
        $(".timepicker2").timepicker({
            minuteStep: 1,
            template: 'modal',
            appendWidgetTo: 'body',
            showSeconds: true,
            showMeridian: false,
            defaultTime: false
        });

        $(".sendingFeedBackTranslate").click(function (e) { // changed.
            e.preventDefault();
            var element = $(this);
            var slug = element.attr("id");
            var name = $('#name').val();
            var timeError = $('#timeError').val();

            $.ajax({
                type: "POST",
                url: "@(Url.Action("Send", "FeedBackTranslate"))",
                data: {
                    slug: slug, name: name, timeError: timeError
                },
                dataType: "json",
                success: function () {
                    //$('#name').hide();
                    //$('#timeError').hide();
                    //$('#id').hide();
                    //$('#name').hide();
                    //$('#pName').hide();
                    //$('#pTimeError').hide();
                    $('.sendFeedBackTranslate').hide();
                    $(".sendingFeedBackTranslate").hide();
                    $('#success').show();
                    //setTimeout(function () {
                    //    alert("Boom!");
                    //}, 2000);
                    setTimeout(function () {
                        $('#name').val("");
                        $('#timeError').val("");
                        $('.sendFeedBackTranslate').show();
                        $('#success').hide();
                        $(".sendingFeedBackTranslate").show();
                    }, 10000);
                }
            });
        });
        $(".sendingProposals").click(function (e) { // changed.
            e.preventDefault();
            var pName = $('#pName').val();
            var pReson = $('#pReson').val();
            $.ajax({
                type: "POST",
                url: "@(Url.Action("Send", "ProposalsFilm"))",
                data: {
                    name: pName, reson: pReson
                },
                dataType: "json",
                success: function () {

                    $('.Proposals').hide();
                    $(".sendingProposals").hide();
                    $('#success1').show();
                    //setTimeout(function () {
                    //    alert("Boom!");
                    //}, 2000);
                    setTimeout(function () {
                        $('#pName').val("");
                        $('#pReson').val("");
                        $('.Proposals').show();
                        $('#success1').hide();
                        $(".sendingProposals").show();
                    }, 10000);
                }
            });
        });

        var per = 0;
        $(document).ready(function () {
            $("#persoff").css("height", $(document).height()).hide();
            $(document).click(function (e) {
                if (!$(e.target).hasClass('switch') && per == 1) {
                    $("#persoff").toggle();
                    per = 0;
                }
            });
            $(".switch").click(function () {
                $("#persoff").toggle();
                per += 1;
                if (per == 2) {
                    per = 0;
                }
            });
        });

    </script>

}
@section Style {
    <link href="~/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet" />
<link href="~/site.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.common-nova.min.css" />
        <link rel="stylesheet" href="~/lib/kendo-ui/styles/kendo.nova.min.css" />
        <script src="https://kendo.cdn.telerik.com/2017.2.621/js/jszip.min.js"></script>
        <script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.all.min.js"></script>
        <script src="https://kendo.cdn.telerik.com/2017.2.621/js/kendo.aspnetmvc.min.js"></script>*@
}

Code/PhimCoDoc/DVMN/Views/Film/_SingleRightPartial.cshtml
@using DVMN.Models.FilmViewModels
@model IEnumerable<SingleRightPartialFilmViewModel>

    <h2 class="text-primary single-right-title">Phim xem nhiều</h2>
    <style>
        .single-right-title {
            margin: 10px;
        }

        .single-right-grid-right a.title {
            color: #337ab7;
        }

        .single-right h3 {
            color: #337ab7;
        }

        .single-right-grid-right p.views {
            color: #333;
        }
    </style>
    <div class="single-grid-right">
        @foreach (var item in Model)
            {
            <div class="single-right-grids">
                <div class="col-md-4 single-right-grid-left">
                    <a asp-controller="Film" asp-action="Single" asp-route-slug="@item.Slug"><img src="@item.Image.Pic182x268" alt="@item.Image.ALT" /></a>
                </div>
                <div class="col-md-8 single-right-grid-right">
                    <a asp-controller="Film" asp-action="Single" asp-route-slug="@item.Slug" class="title"> @item.Title</a>
                    @*<p class="author"><a href="#" class="author">John Maniya</a></p>*@
                    <p class="views">@item.Description</p>
                    <p class="views">Lượt xem @item.Watch</p>
                </div>
                <div class="clearfix"> </div>
            </div>
        }
    </div>